#!/bin/bash 
echo "Generating html files from jemdoc files... " 
python jemdoc.py -c footer.conf "index.jemdoc"
python jemdoc.py -c footer.conf "education.jemdoc"
python jemdoc.py -c footer.conf "research.jemdoc"
python jemdoc.py -c footer.conf "experience.jemdoc"
python jemdoc.py -c footer.conf "honors.jemdoc"
python jemdoc.py -c footer.conf "volunteering.jemdoc"
python jemdoc.py -c footer.conf "gallery.jemdoc"
echo "DONE!\n"